### ISSUE TITLE
[Bug反馈]Fragment ViewModel报错

### ISSUE THREAD

**Issue by Insny** [GangJust/FreedomPlus#26]
### 基本信息

设备信息：Redmi k50u
系统版本：Android 13
模块版本：Freedom+_1.2.3_82
应用版本：抖音_27.6.0_270600
应用ABI：64位

### 如何复现

打开抖音刷了一两个视频就弹出下面这张图片，然后崩溃了

### 截图或视频

![Screenshot_2023-10-30-20-14-05-388_com.freegang.fplus.jpg](https://github.com/GangJust/FreedomPlus/assets/101696117/920ec2f9-d4a8-47f0-9ee7-88b090d83ded)

### 补充说明

如果有其他补充，请在这里自由发挥。

### 崩溃堆栈文本信息

发生错误: Can't access ViewModels from detached fragment
出现时间: 2023-10-30 20:13:42.92
设备信息: Xiaomi 22081212C
系统版本: Android 13 (33)
应用版本: 抖音 27.6.0 (270600)
应用架构: arm64
Google安全补丁级别: 2023-09-01
Dalvik虚拟机: instructionSet=arm64; is64Bit=true
堆栈信息: java.lang.IllegalStateException: Can't access ViewModels from detached fragment
	at androidx.fragment.app.Fragment.getViewModelStore(SourceFile:262179)
	at androidx.lifecycle.ViewModelProvider.<init>(SourceFile:33685504)
	at com.ss.android.ugc.aweme.kiwi.presenter.QContext.vmOfFragment(SourceFile:33947699)
	at X.lDA.LJIIJJI(SourceFile:459113)
	at X.lDA.LJIILL(SourceFile:327735)
	at X.lDA.lambda$a7tMoAClmDC54Ofy5RGuRd5C4uA(Unknown Source:0)
	at X.lDb.invoke(Unknown Source:2)
	at kotlin.jvm.internal.ALambdaS527S0100000_1.invoke$226(SourceFile:17039388)
	at kotlin.jvm.internal.ALambdaS527S0100000_1.invoke(Unknown Source:187)
	at Y.ARunnableS146S0100000_1.run$194(Unknown Source:41)
	at Y.ARunnableS146S0100000_1.run(Unknown Source:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.bytedance.qmi.handler.base.QmiHandler.dispatchMessage(SourceFile:17104921)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by GangJust** [comment]
必现么？不像是模块引起的。

**Comment by Insny** [comment]
> 必现么？不像是模块引起的。

麻了，不知道什么原因今天又出现了
设备信息：Redmi k50u
系统版本：Android 13
模块版本：Freedom+_1.2.4-beta-1_83
应用版本：抖音_27.6.0_270600
应用ABI：64位

发生错误: Can't access ViewModels from detached fragment
出现时间: 2023-10-31 10:55:23.63
设备信息: Xiaomi 22081212C
系统版本: Android 13 (33)
应用版本: 抖音 27.6.0 (270600)
应用架构: arm64
Google 安全补丁级别: 2023-09-01
Dalvik 虚拟机: instructionSet=arm64; is64Bit=true
堆栈信息: java.lang.IllegalStateException: Can't access ViewModels from detached fragment
	at androidx.fragment.app.Fragment.getViewModelStore (SourceFile:262179)
	at androidx.lifecycle.ViewModelProvider.<init>(SourceFile:33685504)
	at com.ss.android.ugc.aweme.kiwi.presenter.QContext.vmOfFragment (SourceFile:33947699)
	at X.lDA.LJIIJJI (SourceFile:459113)
	at X.lDA.LJIILL (SourceFile:327735)
	at X.lDA.lambda$a7tMoAClmDC54Ofy5RGuRd5C4uA (Unknown Source:0)
	at X.lDb.invoke (Unknown Source:2)
	at kotlin.jvm.internal.ALambdaS527S0100000_1.invoke$226 (SourceFile:17039388)
	at kotlin.jvm.internal.ALambdaS527S0100000_1.invoke (Unknown Source:187)
	at Y.ARunnableS146S0100000_1.run$194 (Unknown Source:41)
	at Y.ARunnableS146S0100000_1.run (Unknown Source:106)
	at android.os.Handler.handleCallback (Handler.java:942)
	at android.os.Handler.dispatchMessage (Handler.java:99)
	at com.bytedance.qmi.handler.base.QmiHandler.dispatchMessage (SourceFile:17104921)
	at android.os.Looper.loopOnce (Looper.java:210)
	at android.os.Looper.loop (Looper.java:299)
	at android.app.ActivityThread.main (ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke (Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:954)

**Comment by GangJust** [comment]
目前貌似没有类似错误了，或请尝试最新版版？
