### ISSUE TITLE
[bug反馈] 闪退

### ISSUE THREAD

**Issue by hfuuwcy** [GangJust/FreedomPlus#73]
**日志信息**
模块版本: 1.3.0 (126)
错误信息: parent.findViewById(R.id.poi_single_opt_bg) must not be null
出现时间: 2024-05-20 16:44:58.25
设备信息: Xiaomi 22127RK46C
系统版本: Android 13 (33)
应用版本: 抖音 29.9.0 (290901)
应用架构: arm64
Google安全补丁级别: 2023-09-01
Dalvik虚拟机: instructionSet=arm64; is64Bit=true
堆栈信息: java.lang.NullPointerException: parent.findViewById(R.id.poi_single_opt_bg) must not be null
	at X.0Rsj.<init>(SourceFile:17236211)
	at X.0Rsl.<init>(SourceFile:16908293)
	at X.0RsQ.<init>(SourceFile:100991058)
	at com.ss.android.ugc.aweme.poi.anchor.poi.flavor.PoiFeedAnchor.LJII(SourceFile:196627)
	at kotlin.jvm.internal.ALambdaS617S0100000_18.invoke$267(SourceFile:16908292)
	at kotlin.jvm.internal.ALambdaS617S0100000_18.invoke(Unknown Source:842)
	at kotlin.SynchronizedLazyImpl.getValue(SourceFile:262165)
	at X.0Rse.LJFF(SourceFile:131074)
	at com.ss.android.ugc.aweme.poi.anchor.poi.flavor.PoiFeedAnchor.LIZ(SourceFile:17039363)
	at Y.AObserverS93S0100000_18.onChanged$340(SourceFile:34013219)
	at Y.AObserverS93S0100000_18.onChanged(Unknown Source:1395)
	at X.0rEk$a.onChanged(SourceFile:17039410)
	at androidx.lifecycle.LiveData.considerNotify(SourceFile:17039389)
	at androidx.lifecycle.LiveData.dispatchingValue(SourceFile:17039410)
	at androidx.lifecycle.LiveData.setValue(SourceFile:16973844)
	at androidx.lifecycle.MutableLiveData.setValue(SourceFile:16908294)
	at X.0rEk.setValue(SourceFile:17039390)
	at Y.ARunnableS118S0200000_35.run$44(SourceFile:17104976)
	at Y.ARunnableS118S0200000_35.run(Unknown Source:70)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.bytedance.qmi.handler.base.QmiHandler.dispatchMessage(SourceFile:17104962)
	at com.ss.android.ugc.bytex.async.stack.TransmitHandler.dispatchMessage(SourceFile:16973834)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by hfuuwcy** [comment]
不晓得是哪个控件引起的

**Comment by GangJust** [comment]
官方的问题，开启模块提供的 **拦截崩溃** 即可
