### ISSUE TITLE
bug反馈 打开抖音转圈半天加载不出来

### ISSUE THREAD

**Issue by iBye2mass** [GangJust/FreedomPlus#81]
### 基本信息

设备信息：三星s23+
系统版本：Android 13
模块框架：Lsposed
模块版本：freedom+_1.3.0_123
应用版本：抖音_27.4.0_270401
应用ABI：64位

### 如何复现

选择作用域后进入抖音视频加载的特别慢，有时候视频加载出来评论区也出不来，滑动下一个视频也特别慢转圈圈，商城搜索也会这样

### 截图或视频

https://github.com/GangJust/FreedomPlus/assets/129377587/346fc3e3-908a-4ac7-aefa-18ccc6c8bb82

### 补充说明

抖音是29.7版本登录后用核心破解覆盖到27.4.0的

### 崩溃堆栈文本信息

[ 2024-06-10T04:13:06.474    10383: 17111: 17111 I/LSPosed-Bridge  ] Freedom+: 
╭───────────────────────────────
├─java.lang.NoSuchMethodException: No method in the target class meets the following conditions!
├─entity: o00O0O0o.o00O00o0#methodBefore
├─names: 
├─params: int, java.lang.String
├─return: 
╰───────────────────────────────
[ 2024-06-10T04:13:06.512    10383: 17111: 17111 I/LSPosed-Bridge  ] Freedom+: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.ss.android.ugc.aweme.homepage.tab.business.bottom.HomeBottomTabServiceImpl
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:12)
	at io.github.xpler.core.entity.OooO0O0.findClass(HookEntity.kt:12)
	at io.github.xpler.core.entity.OooO0O0.findClass$default(HookEntity.kt:8)
	at o00O0O0o.o0000O0.setTargetClass(HHomeBottomTabServiceImpl.kt:5)
	at io.github.xpler.core.entity.OooO0O0.<init>(HookEntity.kt:6)
	at io.github.xpler.core.entity.OooO0O0.<init>(HookEntity.kt:29)
	at o00O0O00.OooOO0O.<init>(BaseHook.kt:3)
	at o00O0O0o.o0000O0.<init>(HHomeBottomTabServiceImpl.kt:1)
	at o00O0O0o.OooOO0.run(R8$$SyntheticClass:58)
	at o00O0O0o.OooOO0O.<init>(DouYinMain.kt:113)
	at io.github.fplus.HookInit.onCreateAfter(HookInit.kt:13)
	at io.github.xpler.OooO00o$OooO00o$OooO0O0.invoke(HookEntrance.kt:3)
	at io.github.xpler.OooO00o$OooO00o$OooO0O0.invoke(HookEntrance.kt:1)
	at io.github.xpler.core.impl.OooO0O0$OooO0O0.afterHookedMethod(MethodHookImpl.kt:14)
	at de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:294)
	at LSPHooker_.onCreate(Unknown Source:8)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
	at com.ss.android.ugc.route_monitor.impl.RouteInstrumentation.callApplicationOnCreate(SourceFile:16973834)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7619)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2400)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.ClassNotFoundException: com.ss.android.ugc.aweme.homepage.tab.business.bottom.HomeBottomTabServiceImpl
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at q.a(Unknown Source:16)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:4)
	... 28 more
Caused by: java.lang.ClassNotFoundException: com.ss.android.ugc.aweme.homepage.tab.business.bottom.HomeBottomTabServiceImpl
	at o00O0oO.oOOO0OO0.loadClass(XplerClassloader.kt:55)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 32 more
[ 2024-06-10T04:13:06.618    10383: 17111: 17111 I/LSPosed-Bridge  ] Freedom+: version: 1.3.0 - 27.4.0(270401)

**Comment by GangJust** [comment]
不要降级覆盖安装，或者降级之后清除一下抖音数据。
